### ISSUE TITLE
The newly-added line which sets ENV['ORIGINAL_ENV'] is breaking things

### ISSUE THREAD

**Issue by ctrevorrow** [Shopify/homebrew-shopify#367]
https://github.com/Shopify/homebrew-shopify/blob/1c3cb2958bc578b1f078fae177de5f6507c5f107/shopify-cli.rb#L101

After upgrading to v2.15.3, I ran `Shopify Theme Serve` and received this error:  ```/usr/local/bin/shopify:2:in `<main>': undefined method `to_json' for {"PATH"=>"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", [...omitted...], "_"=>"/usr/local/bin/shopify"}:Hash (NoMethodError)```

The line `ENV['ORIGINAL_ENV']=ENV.to_h.to_json` seems to be what's causing the issue.  This line is not present in v2.15.2, which works correctly.

I am using an Apple M1 Pro-based MacBook.  I am noting this in case the issue is specific to the architecture.  I've not tested it on Intel.
